version: "3"
services:
  phoenix:
    build:
      context: .
    volumes:
      # Include the current directory, so we can change stuff without having to build the container again.
      - ".:/app"
      # Mount these directories to guarantee that they are empty and do not contain any OS specific binaries.
      - "/app/_build"
    # Override the Dockerfile command for the development container not to exit, in case elixir encounters an error.
    command: "bash -c 'mix phx.server; tail -f /dev/null'"
    environment:
      DATABASE_URL: "mysql://mysql:mysql@db:3306/elph_shell_dev"
      TEST_DATABASE_URL: "mysql://mysql:mysql@db_test:3306/elph_shell_test"
      SECRET_KEY_BASE: "/XMvp9CUulBOqCx1rluCp9cz7ZX+edv5zvNEEtKtXYnZ3kVhPF2cEb/BFRU4m76s"
      SMTP_HOST: smtp
      SMTP_PORT: 1025
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: elph_shell_dev

  db_test:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: elph_shell_test

  smtp:
    image: mailhog/mailhog:v1.0.1
    ports:
      # SMTP Port
      - 1025:1025
      # Web Port
      - 8025:8025
